#!/bin/bash
# /etc/init.d/ampabooks

### BEGIN INIT INFO
# Provides:          ampabooks
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Ampabooks initscript
# Description:       This service is used to manage the ampabooks application
### END INIT INFO


case "$1" in 
    start)
        echo "Starting ampabooks ..."
        cd /home/pi/ampabooks
        python app.py 80 >> /home/pi/ampabooks.log 2>&1 &
        ;;
    stop)
        echo "Stopping ampabooks ..."
        kill -9 $(ps aux | grep -v grep | grep app.py | awk '{print $2}')
        ;;
    *)
        echo "Usage: /etc/init.d/ampabooks start|stop"
        exit 1
        ;;
esac

exit 0
